### ISSUE TITLE
General TODO list for 1.0.0

### ISSUE THREAD

**Issue by jamierocks** [EthanRiley/PastPapers#7]
This issue is meant to track the tasks which must be completed before an initial release will be possible.
## Functionality
- [ ] Be able to search through all the papers
  - [ ] by name
  - [ ] by subject
  - [ ] by date
- [ ] Parse pdf document
  - [ ] Parse written questions
  - [ ] Parse multiple-choice questions

**Comment by UnkDevE** [comment]
hmm, depends how we interline the search feature, if we just want to be able to search using dates etc... or tags or single search for each one/seprate widgets etc...
